server:
 port: ${PORT:8888}
 
spring:
 cloud:
  config:
   server:
    git:
     uri: file://${HOME}/Snapshotviews/git/ce-ui-portal-properties
 autoconfigure:
  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
   org:
    springframework: INFO